---
- name: install python-passlib for adding httpasswd entries
  yum: name=python-passlib state=present
  when: osbs_proxy_htpasswd_users != [] and ansible_pkg_mgr == "yum"

- name: install python-passlib for adding httpasswd entries
  dnf: name=python-passlib state=present
  when: osbs_proxy_htpasswd_users != [] and ansible_pkg_mgr == "dnf"

- name: initialize htpasswd file
  htpasswd:
    path: "{{ osbs_proxy_htpasswd_file }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    owner: "{{ osbs_proxy_secrets_owner }}"
    group: "{{ osbs_proxy_secrets_group }}"
    mode: "{{ osbs_proxy_secrets_perms }}"
    setype: "{{ osbs_proxy_secrets_setype }}"
  with_items: osbs_proxy_htpasswd_users
