---
- name: install mod_auth_kerb
  yum: name=mod_auth_kerb state=present
  when: ansible_pkg_mgr == "yum"

- name: install mod_auth_kerb
  dnf: name=mod_auth_kerb state=present
  when: ansible_pkg_mgr == "dnf"

- name: set permissions on kerberos keytab
  file:
    path: "{{ osbs_proxy_kerberos_keytab_file }}"
    state: file
    owner: "{{ osbs_proxy_secrets_owner }}"
    group: "{{ osbs_proxy_secrets_group }}"
    mode: "{{ osbs_proxy_secrets_perms }}"
    setype: "{{ osbs_proxy_secrets_setype }}"
