---
- name: set permissions on kerberos keytab
  file:
    path: "{{ osbs_proxy_kerberos_keytab_file }}"
    state: file
    owner: "{{ osbs_proxy_secrets_owner }}"
    group: "{{ osbs_proxy_secrets_group }}"
    mode: "{{ osbs_proxy_secrets_perms }}"
    setype: "{{ osbs_proxy_secrets_setype }}"
